spring.application.name=demo
spring.datasource.url=jdbc:h2:file:/transaction;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=0682
spring.sql.init.mode=never



spring.liquibase.change-log=classpath:liquibase/changelog-master.yml



spring.dynamic-datasource.url=jdbc:h2:file:/dynamic_rules;MODE=PostgreSQL
spring.dynamic-datasource.driver-class-name=org.h2.Driver
spring.dynamic-datasource.username=sa
spring.dynamic-datasource.password=0682
spring.dynamic-sql.init.mode=never

